[package]
name = "hydroconf"
version = "0.1.0"
authors = ["Michele Lacchia <michelelacchia@gmail.com>"]
license = "MIT"
edition = "2018"

description = "Configuration management for Rust."
homepage = "https://github.com/rubik/hydroconf"
repository = "https://github.com/rubik/hydroconf"
keywords = ["configuration", "12factorapp", "settings"]

[dependencies]
config = "0.9"
serde = "1.0"
